#3 Remove useless nightly- prefix.

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -44,8 +44,15 @@ jobs:
       - name: Get NIGHTLY_VERSION from _VERSION
         id: version
         run: |
-          echo "NIGHTLY_VERSION=$(cat ./source/_VERSION)" >> $GITHUB_ENV
-          echo "NIGHTLY_VERSION=$(cat ./source/_VERSION)" >> $GITHUB_OUTPUT
+          VERSION_FILE="./source/_VERSION"
+          if [ -f "$VERSION_FILE" ]; then
+            echo "NIGHTLY_VERSION=$(cat ./source/_VERSION)" >> $GITHUB_ENV
+            echo "NIGHTLY_VERSION=$(cat ./source/_VERSION)" >> $GITHUB_OUTPUT
+          fi
+          if [ -z "$NIGHTLY_VERSION" ]; then
+            echo "Cannot load NIGHTLY_VERSION from $VERSION_FILE"
+            exit 1
+          fi
       
       - name: Create and Upload Release Assets
         uses: softprops/action-gh-release@v2
@@ -55,10 +62,10 @@ jobs:
           draft: true
           prerelease: false
           files: |
-            ./dist/docx/nightly-DENT-OIP.docx
-            ./dist/pdf/nightly-DENT-OIP.pdf
-            ./dist/nightly-codes.csv
-            ./dist/nightly-views.csv
+            ./dist/docx/DENT-OIP.docx
+            ./dist/pdf/DENT-OIP.pdf
+            ./source/tables/codes.csv
+            ./source/tables/views.csv
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Publish HTML to gh-pages branch
